name: Deploy Homelab i5

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Conectar na Rede Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          ephemeral: true # Garante que o runner suma do painel após o deploy

      - name: Executar Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: dyone
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Caminho absoluto para o projeto nesta máquina
            cd /home/dyone/controlefinanceiro
            
            # Atualiza o código via Git
            git pull origin main
            
            # Reconstrói os containers conforme definido no docker-compose.yml
            docker compose up -d --build
            
            # Limpa imagens antigas para não encher o disco
            docker image prune -f